[google_oauth]
client_id = "308161352982-u2jhji1lcqqb42o7oql0me3nat6l3efp.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://mst-kpi.streamlit.app"
allowed_users = [
  "fp71612@gmail.com",
  "fabio89608@gmail.com",
  "124453221s@gmail.com",
  "yolu902@gmail.com",
  "a6108568@gmail.com",
  "Wmksue12976@gmail.com",
  "aqianyu8@gmail.com",
  "happy0623091@gmail.com",
  "cvcv0897@gmail.com",
  "minkatieweng@gmail.com",
  "a0956505289@gmail.com",
  "Noncks@gmail.com",
  "vicecolife0969@gmail.com",
  "life8ray@gmail.com",
  "inthing123@gmail.com",
  "leslie641230@gmail.com",
  "ainstaccc@gmail.com",
  "life8x35@gmail.com",
  "allwears04@gmail.com",
  "life8x33@gmail.com",
  "allwears05@gmail.com",
  "allwears08@gmail.com",
  "allwears10@gmail.com",
  "allwears16@gmail.com",
  "allwears20@gmail.com",
  "allwears07@gmail.com",
  "allwears15@gmail.com",
  "boylondonx02@gmail.com",
  "boylondonx03@gmail.com",
  "boylondonx01@gmail.com",
  "boylondonx04@gmail.com",
  "life8x17@gmail.com",
  "life8x23@gmail.com",
  "life8x30@gmail.com",
  "life8x38@gmail.com",
  "life8x18@gmail.com",
  "life8x63@gmail.com",
  "life8x46@gmail.com",
  "life8x29@gmail.com",
  "life8x56@gmail.com",
  "life8x16@gmail.com",
  "lc001@life8.com.tw",
  "life8x34@gmail.com",
  "life8x45@gmail.com",
  "lm040@life8.com.tw",
  "life8x25@gmail.com",
  "life8x36@gmail.com",
  "lm038@life8.com.tw",
  "life8x60@gmail.com",
  "life8x64@gmail.com",
  "life8x65@gmail.com",
  "life8x31@gmail.com",
  "life8x41@gmail.com",
  "life8x40@gmail.com",
  "life8x48@gmail.com",
  "life8x13@gmail.com",
  "life8x19@gmail.com",
  "life8x39@gmail.com",
  "life8x43@gmail.com",
  "life8x57@gmail.com",
  "life8x58@gmail.com",
  "lm039@life8.com.tw",
  "life8x61@gmail.com",
  "life8x66@gmail.com",
  "life8x28@gmail.com",
  "life8x20@gmail.com",
  "life8x14@gmail.com",
  "life8x21@gmail.com",
  "life8x42@gmail.com",
  "life8x47@gmail.com",
  "lm037@life8.com.tw",
  "life8x69@gmail.com",
  "life8x12@gmail.com",
  "life8x24@gmail.com",
  "life8x03@gmail.com",
  "life8x32@gmail.com",
  "life8x62@gmail.com",
  "life8x67@gmail.com",
  "mollifix08@gmail.com",
  "mollifix01@gmail.com",
  "mollifix03@gmail.com",
  "mollifix04@gmail.com",
  "mollifix06@gmail.com",
  "mollifix07@gmail.com",
  "mollifix09@gmail.com",
  "mollifix10@gmail.com",
  "nonspace02@gmail.com",
  "nonspace03@gmail.com",
  "wildmeet02@gmail.com",
  "wildmeet10@gmail.com",
  "wildmeet11@gmail.com",
  "wildmeet08@gmail.com",
  "wildmeet09@gmail.com",
  "wildmeet07@gmail.com",
  "wildmeet13@gmail.com",
  "wildmeet14@gmail.com",
  "wildmeet15@gmail.com",
  "wildmeet03@gmail.com",
  "wildmeet04@gmail.com",
  "wildmeet06@gmail.com",
  "wildmeet12@gmail.com"
]
